### PR TITLE
Fix context validation issue

### PR DESCRIPTION
**Pull request by koptan**
This PR includes fixing the context verification issue and disabling the Revocation List because we are not using the final standard.

### CODE REVIEW

**Review by PManaras — COMMENTED** [review]
The remoteCache is initialized with null in RemoteDocumentLoader and is not set when retrieving the instance in the JsonLdValidatorImpl, either. This way the document will not be retrieved from the cache.

**Review by PManaras — COMMENTED** [review]
This should do the trick

**Review by borisrizov-zf — APPROVED** [review]
All seems good.

**Comment by borisrizov-zf** [comment]
@koptan please update the app version.

**Review by DominikPinsel — APPROVED** [review]
Thank you for fixing this and sorry for the late review :)

**Pull request merged**
